### PR TITLE
General cleanup and boilerplate code reduction

### PR DESCRIPTION
**Pull request by CraftedMods**
I applied the formatting rules you've specified to all files, fixed some compiler warnings and removed boilerplate code (I replaced calls of [...].addChatMessage([...]) with the functions of PvpUtils). Furthermore I extended these functions to accept several lines of text, which prevents a even larger set of boilerplate code.
Are pull requests like this ok for you, or do you only want receive pull requests containing "important" features?

### CODE REVIEW

**Comment by Mahtaran** [comment]
Also, 👍🏻👍🏻👍🏻

**Comment by VulcanForge** [comment]
Are you sure these are the formatting settings I attached to the repository?

**Comment by CraftedMods** [comment]
Yes. See this [screenshot](https://i.imgur.com/cc55Ahj.png).

**Comment by VulcanForge** [comment]
Something is wrong with the formatting options I provided for you then. For example, I like to have a space between a method name and its arguments/parameters. But your commit has removed all those spaces and wrapped lines in a truly diabolical fashion. The rest of your changes are fine though. I will re-upload my Eclipse settings in a few hours if I remember.

**Comment by CraftedMods** [comment]
I noticed that the spaces in the method declarations were removed, but added at method invocations.

**Pull request merged**
