### PR TITLE
Added a header and a footer to the /pvplist player list

### LINKED ISSUE #66: Add a header and a footer to the /pvplist list

### PR DESCRIPTION
**Pull request by CraftedMods**
Closes #66.

### CODE REVIEW

**Comment by CraftedMods** [comment]
Yes. But you should be glad about these types of PRs. Wait for the PR for the biome overrides. It's huge.

**Comment by Mahtaran** [comment]
Oh I was being sarcastic in a humoristic way, I know that sometimes the small changes are very important.

Also frick I'm afraid now

**Comment by CraftedMods** [comment]
I know it was sarcastic. Mine was too, but without using special formatting or emojies is can be hard to see.

**Comment by Mahtaran** [comment]
😂

**Pull request merged**
