### PR TITLE
Change the help message of /pvplist

### LINKED ISSUE #175: help text with /pvplist: all players with pvp mode on
The text now says it shows all hostile players, but that isn't correct. It shows all players with PvP Mode ON, or 'all players available for PvP'.

### PR DESCRIPTION
**Pull request by Mahtaran**
Fixes #175

### CODE REVIEW

**Comment by CraftedMods** [comment]
We should first discuss #175.

**Comment by CraftedMods** [comment]
See the last comment in #175 for the fix.

**Comment by CraftedMods** [comment]
I can also apply the fix, if you're okay with it.

**Comment by CraftedMods** [comment]
Dou you want to merge it?

**Comment by Mahtaran** [comment]
If you could 😉

**Pull request merged**
