### PR TITLE
Set the PvP Timer to 0 on a player death

### LINKED ISSUE #176: Cancel PvP combat status upon any death event
Currently the pvp combat timer isn't affected when a death event occurs. A player respawning after a death event should no longer be in active combat status.

### PR DESCRIPTION
**Pull request by Mahtaran**
Fixes #176

### CODE REVIEW

**Comment by CraftedMods** [comment]
The PR must only contain what is in it's scope. So for the typo you would have to create a new PR. And it isn't a typo. I wrote "disableable" because that feature can be disabled, but don't has to be. Please remove the fix of the typo.

**Comment by CraftedMods** [comment]
Do you want to merge the PR? If yes, do a **squash-merge** and add `Closed #176` as commit message and `PR #179` as commit description.

**Comment by CraftedMods** [comment]
Should I merge this too?

**Comment by Mahtaran** [comment]
Would be nice if you could

**Pull request merged**
